(function(g){var window=this;'use strict';var hZa=function(a,b){var c=[];return g.bs(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},K3=function(a,b){return"getAll"in IDBIndex.prototype?g.Qr(a.j.getAll(b,void 0)):hZa(a,b)},iZa=function(a,b){return g.Wr(a,["captions"],{mode:"readonly",
jc:!0},function(c){return g.uoa(c.objectStore("captions"),b)})},jZa=function(a){var b=new g.Jw("und",new g.jz("Default","und",!0));
b.captionTracks=a.captionTracks;return b},kZa=function(a){return new g.Sg(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},h=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.ida(m,g.Ta(f,l),h);
else b(e)})},L3=function(a){this.j=a},M3=function(){L3.apply(this,arguments)},N3=function(){M3.apply(this,arguments)},O3=function(){M3.apply(this,arguments)},P3=function(){M3.apply(this,arguments)},Q3=function(){L3.apply(this,arguments)},R3=function(){M3.apply(this,arguments)},S3=function(){M3.apply(this,arguments)},T3=function(){M3.apply(this,arguments)},U3=function(){M3.apply(this,arguments)},V3=function(){M3.apply(this,arguments)},W3=function(){M3.apply(this,arguments)},X3=function(){M3.apply(this,
arguments)},Y3=function(){L3.apply(this,arguments)},Z3=function(){M3.apply(this,arguments)},$3=function(){M3.apply(this,arguments)},a4=function(){M3.apply(this,arguments)},b4=function(){M3.apply(this,arguments)},c4=function(){M3.apply(this,arguments)},d4=function(){M3.apply(this,arguments)},e4=function(){M3.apply(this,arguments)},f4=function(){L3.apply(this,arguments)},g4=function(){M3.apply(this,arguments)},h4=function(){M3.apply(this,arguments)},i4=function(){M3.apply(this,arguments)},j4=function(){M3.apply(this,
arguments)},k4=function(){M3.apply(this,arguments)},l4=function(){M3.apply(this,arguments)},m4=function(){M3.apply(this,arguments)},n4=function(){M3.apply(this,arguments)},o4=function(){M3.apply(this,arguments)},p4=function(){M3.apply(this,arguments)},q4=function(){M3.apply(this,arguments)},r4=function(){M3.apply(this,arguments)},s4=function(){M3.apply(this,arguments)},t4=function(){M3.apply(this,arguments)},u4=function(){M3.apply(this,arguments)},v4=function(){M3.apply(this,arguments)},w4=function(){M3.apply(this,
arguments)},x4=function(){M3.apply(this,arguments)},y4=function(){M3.apply(this,arguments)},z4=function(){M3.apply(this,arguments)},A4=function(){M3.apply(this,arguments)},B4=function(){M3.apply(this,arguments)},C4=function(){M3.apply(this,arguments)},D4=function(){M3.apply(this,arguments)},E4=function(){M3.apply(this,arguments)},F4=function(){M3.apply(this,arguments)},G4=function(){M3.apply(this,arguments)},H4=function(){M3.apply(this,arguments)},I4=function(){M3.apply(this,arguments)},J4=function(){M3.apply(this,
arguments)},K4=function(){M3.apply(this,arguments)},L4=function(){M3.apply(this,arguments)},M4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},lZa=function(){if(N4)return N4();
var a={};N4=g.As("PersistentEntityStoreDb",{gs:(a.EntityStore={Ro:1},a.EntityAssociationStore={Ro:2},a),Ez:!1,upgrade:function(b,c){c(1)&&g.Zr(g.Ur(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.Ur(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.Zr(b,"byParentEntityKey","parentEntityKey"),g.Zr(b,"byChildEntityKey","childEntityKey"))},
version:3});return N4()},mZa=function(a){return g.es(lZa(),a)},O4=function(a,b){b=void 0===b?{}:b;
g.Ar.call(this,g.YUa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,O4.prototype)},nZa=function(a){return new O4("WRONG_DATA_TYPE",{mW:a})},oZa=function(a){return a instanceof Error?new O4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new O4("UNKNOWN_ENCODE_ERROR")},pZa=function(a){return a instanceof Error?new O4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new O4("UNKNOWN_DECODE_ERROR")},qZa=function(a,b){a=a instanceof
O4?a:b(a);
g.S(a);throw a;},rZa=function(){},sZa=function(a,b,c){try{return a.B(b,c)}catch(d){qZa(d,oZa)}},P4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},Q4=function(a){this.j=a},uZa=function(a){var b=tZa[a];
if(b)return b;g.Bu(new g.Ar("Entity model not found.",{entityType:a}))},vZa=function(a,b){this.j=a;
this.u=b;this.B={}},S4=function(a,b){a:{a=R4(a.u,b.version);
try{var c=a.u(b.data,b.key);break a}catch(d){qZa(d,pZa)}c=void 0}return c},T4=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return S4(a,d)}})},U4=function(a,b,c){return c?(c=c.map(function(d){return T4(a,d,b)}),g.Mr.all(c)):K3(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return S4(a,e)})})},W4=function(a,b,c){var d=M4(b),e=R4(a.u,1),f=Object.assign({},b);
return a.j.objectStore("EntityStore").get(d).then(function(h){if(h){if(h.entityType!==c)throw Error("Incorrect entity type");f.entityMetadata||(h=S4(a,h),f.entityMetadata=h.entityMetadata)}}).then(function(){var h={key:d,
entityType:c,data:sZa(e,f,d),version:1};return g.Mr.all([g.Xr(a.j.objectStore("EntityStore"),h),wZa(a,f,c)])}).then(function(){V4(a,d,c);
return d})},X4=function(a,b,c){b=b.map(function(d){return W4(a,d,c)});
return g.Mr.all(b)},Y4=function(a,b,c){if(null==c?0:c.du){var d=new Set;
return xZa(a,b,d).then(function(){for(var f=[],h=g.r(d),l=h.next();!l.done;l=h.next())f.push(Y4(a,l.value));return g.Mr.all(f).then(function(){})})}var e=g.FC(b).entityType;
return g.Mr.all([a.j.objectStore("EntityStore").delete(b),Z4(a,b)]).then(function(){V4(a,b,e)})},yZa=function(a,b){return g.bs(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Mr.all([c.delete(),
Z4(a,c.KB())]).then(function(){V4(a,c.KB(),b);return c.continue()})})},zZa=function(a,b,c,d){var e=R4(a.u,1);
return T4(a,b,d).then(function(f){if(f){f=g.pC(f,c);var h={key:b,entityType:d,data:sZa(e,f,b),version:1};return g.Mr.all([g.Xr(a.j.objectStore("EntityStore"),h),wZa(a,f,d)])}}).then(function(){V4(a,b,d);
return b})},V4=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},AZa=function(a,b,c){var d=M4(b);
c=uZa(c);if(!c)return g.Mr.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.u());for(var e=c.next();!e.done;e=c.next())b.push(g.Xr(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Mr.all(b).then(function(f){return f.map(function(h){return h[1]})})},Z4=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},wZa=function(a,b,c){var d=M4(b);
return Z4(a,d).then(function(){return AZa(a,b,c)})},xZa=function(a,b,c){if(c.has(b))return g.Mr.resolve(void 0);
c.add(b);return BZa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Mr.resolve(void 0),f={};
d=g.r(d);for(var h=d.next();!h.done;f={YD:f.YD},h=d.next())f.YD=h.value,e=e.then(function(l){return function(){return xZa(a,l.YD,c)}}(f));
return e}).then(function(){})},BZa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return K3(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(K3(c.index("byChildEntityKey"),f.childEntityKey));return g.Mr.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},$4=function(){},CZa=function(){this.j={};
this.j[0]=new $4;if(!g.Q("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.Br();var c=P4(b);var d=new Q4(new g.zA(c),new g.yA(c))}catch(e){throw a=e instanceof Error?new O4("KEY_CREATION_FAILED",{originalMessage:e.message}):new O4("KEY_CREATION_FAILED"),g.S(a),a;}a[1]=d}},R4=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new O4("INVALID_ENCODER_VERSION",{mW:b}),g.S(b),b;return a},a5=function(a,b){g.I.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.Br());a.onmessage=this.B.bind(this);this.channel=a},b5=function(a,b,c){var d,e,f,h;
return g.B(function(l){if(1==l.j)return g.A(l,mZa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.Wr(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new vZa(m,a.u);return c(e)}),3);
f=l.u;e&&(h=e.B,0<Object.keys(h).length&&(a.channel.postMessage(h),DZa(a,h)));return l.return(f)})},c5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},d5=function(a,b,c){return b5(a,{mode:"readwrite",
jc:!0},function(d){return W4(d,b,c)})},EZa=function(a,b){return b5(a,{mode:"readwrite",
jc:!0},function(c){return X4(c,b,"offlineOrchestrationActionWrapperEntity")})},FZa=function(a,b){return b5(a,{mode:"readwrite",
jc:!0},function(c){return Y4(c,b)})},e5=function(a,b,c){return b5(a,{mode:"readonly",
jc:!0},function(d){return T4(d,b,c)})},f5=function(a,b,c){return b5(a,{mode:"readonly",
jc:!0},function(d){return U4(d,b,c)})},DZa=function(a,b){a=g.r(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},GZa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.wa(d,2),g.A(d,g.ls(),4);if(2!=d.j){a=d.u;if(!a||!g.Cr()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new CZa;return d.return(new a5(a,b))}c=g.ya(d);c instanceof Error&&g.S(c);return d.return()})},h5=function(){g5||(g5=GZa());
return g5},HZa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},IZa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,h5(),2):(b=c.u)?g.A(c,b5(b,"readwrite",function(d){for(var e={},f={},h=g.r(a),l=h.next();!l.done;f={nh:f.nh,ut:f.ut},l=h.next())f.nh=l.value,f.nh.entityKey&&HZa(f.nh)&&(f.ut=g.Me(f.nh.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.nh.type&&(l=function(m){return function(){return W4(d,m.nh.payload[m.ut],m.ut)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.nh.type&&(l=function(m){return function(){return Y4(d,m.nh.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.nh.type&&(l=function(m){return function(){return zZa(d,m.nh.entityKey,m.nh.payload[m.ut],m.ut)}}(f)),l&&(e[f.nh.entityKey]=e[f.nh.entityKey]?e[f.nh.entityKey].then(l):l()));
return g.Mr.all(Object.values(e))}),0):c.return()})},JZa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.vD){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.vD.dispatch(d)}return g.A(c,IZa(b),2)}b.length=0;g.va(c)})},KZa=function(a){return void 0!==a},LZa=function(a){var b=g.QC();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.Ewa(b);JSON.stringify(b);return b},MZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.ls(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.TC(b),3):d.return();c=d.u;return d.return(g.Wr(c,["index","media","captions"],{mode:"readwrite",jc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Mr.all(e).then(function(){})}))})},NZa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.ls(),2);if(3!=c.j){a=c.u;if(!a)throw g.Kr("rvdfd");return g.A(c,g.TC(a),3)}b=c.u;return c.return(g.Wr(b,["index","media"],{mode:"readwrite",jc:!0},function(d){var e={};return g.$r(d.objectStore("index"),{},function(f){var h=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Mr.resolve(void 0);if(h){var m=h[1];h=h[2];e[m]=e[m]||{};var n;e[m][h]=g.Jwa(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Mr.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},h=g.r(Object.keys(e)),l=h.next();!l.done;l=h.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=LZa(f);return g.xoa(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.Nwa);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},OZa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.ls(),2);if(3!=e.j){c=e.u;if(!c)throw g.Kr("wct");return g.A(e,g.TC(c),3)}d=e.u;return g.A(e,g.Wr(d,["captions"],{mode:"readwrite",jc:!0},function(f){var h=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.Xr(f,b[l],a+"|"+b[l].metadata.vss_id);h.push(m)}return g.Mr.all(h)}),0)})},PZa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.ls(),2);if(3!=e.j){c=e.u;if(!c)throw g.Kr("gactfv");return g.A(e,g.TC(c),3)}d=e.u;return e.return(iZa(d,b))})},QZa=function(a){return g.B(function(b){g.SC(a,0);
return b.return(MZa(a))})},RZa=function(a){return{context:g.TF(),
videoIds:a}},SZa=function(a){return{context:g.TF(),
playlistIds:a}},i5=function(a,b,c){g.Bu(new g.Ar("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.Bu(b)},TZa=function(a){var b,c,d,e,f,h,l,m,n,p,q,t,u,x,y,z,D;
return g.B(function(H){if(1==H.j)return g.A(H,b5(a,{mode:"readonly",jc:!0},function(G){return U4(G,"playbackData").then(function(L){var aa=L.map(function(sa){return sa.transfer}).filter(function(sa){return!!sa}),M=L.map(function(sa){return sa.offlineVideoPolicy}).filter(function(sa){return!!sa});
aa=U4(G,"transfer",aa);M=U4(G,"offlineVideoPolicy",M);return g.Mr.all([aa,M]).then(function(sa){var za=g.r(sa);sa=za.next().value;za=za.next().value;return[L,sa,za]})})}),2);
b=H.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;h=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(u=t.value)&&(n[u.key]=u);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);D=h.map(function(G){var L=n[G.transfer],aa=p[G.offlineVideoPolicy];G=g.FC(aa.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===aa.action){var M="OFFLINE_VIDEO_STATE_DISABLED";aa.expirationTimestamp&&Number(aa.expirationTimestamp)<Date.now()/1E3&&(M="OFFLINE_VIDEO_STATE_EXPIRED");
aa=M}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===aa.action)aa="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==L?void 0:L.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":M="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":M="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":M="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":M="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":M=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":M="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:M="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===M)switch(null==L?void 0:L.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":M="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":M="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":M="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}aa=M}G={id:G,videoState:aa};if(null==L?0:L.cotn)G.cotn=L.cotn;if(null==L?0:L.maximumDownloadQuality)G.selectedVideoQuality=null==L?void 0:L.maximumDownloadQuality;return G});
return H.return({offlineVideos:D})})},UZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,TZa(a),2);b=c.u;g.vr("offlineStateSnapshot",b);g.va(c)})},j5=function(a){g.I.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.Br()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.Br()),this.u.onmessage=this.C.bind(this))},k5=function(a,b){a.api.La("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},VZa=function(){this.locks=navigator.locks},WZa=function(){try{var a=g.La("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new VZa,g.Ka("ytglobal.locks_",a),a}catch(d){}},YZa=function(a,b,c,d){var e=this;
this.N=a;this.V=b;this.visibility=c;this.K=d;this.C=this.I=this.D=this.u=this.j=!1;this.J=new g.K(function(){XZa(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.uf()})},ZZa=function(a){if(!a.u&&!a.j){var b=WZa();
if(b){a.u=!0;var c=g.Br("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,h;return g.B(function(l){switch(l.j){case 1:return g.wa(l,2),a.B=new g.qi,a.j=!0,a.u=!1,g.A(l,a.N(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.xa(l,0);break;case 2:d=g.ya(l),(null==(f=(e=a).K)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||XZa(a),d instanceof Error&&(h=d,h.args=[{name:"WoLockManagerError",MC:d.name}],g.S(h)),g.va(l)}})})}}},$Za=function(a){a.j&&(a.C=
!0,l5(a))},a_a=function(a,b){a.j&&(a.D=b,l5(a))},b_a=function(a,b){a.j&&(a.I=b,l5(a))},l5=function(a){a.I&&a.D&&a.C&&a.visibility.isBackground()?g.Fn(a.J,6E4):a.J.stop()},XZa=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.V()},m5=function(a,b){var c=b.mj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.vr("offlineTransferStatusChanged",a)},c_a=function(a,b,c,d){b=Math.floor(b/1024).toFixed();
m5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!!d,alreadyDownloadedKbytes:b,totalFetchedKbytes:b,totalContentKbytes:Math.floor(c/1024).toFixed()},a)},d_a=function(a){m5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},e_a=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
n5=function(){},o5=function(){},p5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.Br("CacheStorage get")},f_a=function(){return g.B(function(a){if(void 0!==q5)return a.return(q5);
q5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.wa(d,2),g.A(d,r5.open("test-only"),4);case 4:return g.A(d,r5.delete("test-only"),5);case 5:g.xa(d,3);break;case 2:if(c=g.ya(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.va(d)}})});
return a.return(q5)})},t5=function(){return g.B(function(a){if(1==a.j)return g.A(a,f_a(),2);
if(!a.u)return a.return(void 0);s5||(s5=new o5);return a.return(s5)})},g_a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,t5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},u5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,t5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},v5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,t5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},w5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},x5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},y5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},z5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&!!a.entityKey},D5=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,za,ba,qa,fb,bb,ub,vb,tc;
return g.B(function(kb){switch(kb.j){case 1:return e=g.GC(a,"ytMainVideoEntity"),f=g.GC(a,"mainVideoEntity"),h=g.GC(a,"ytMainChannelEntity"),l=g.GC(a,"transfer"),g.A(kb,b5(b,{mode:"readonly",jc:!0},function(Sb){return g.Mr.all([T4(Sb,e,"ytMainVideoEntity"),T4(Sb,f,"mainVideoEntity"),T4(Sb,h,"ytMainChannelEntity"),T4(Sb,l,"transfer"),U4(Sb,"ytMainChannelEntity"),U4(Sb,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:m=kb.u;n=g.r(m);p=n.next().value;q=n.next().value;t=n.next().value;u=n.next().value;x=n.next().value;y=n.next().value;z=p;D=q;H=t;G=u;L=x;aa=y;if(!(z||D||H)){kb.Ra(3);break}M=z?A5(z.thumbnail):D?A5(D.thumbnail):[];if(!H){sa=[];kb.Ra(4);break}return g.A(kb,h_a(H,L),5);case 5:sa=kb.u;case 4:return za=sa,g.A(kb,u5(M.concat(za)),3);case 3:ba=[];qa=g.GC(a,"ytMainDownloadedVideoEntity");fb=g.GC(a,"mainVideoEntity");bb=g.r(aa);for(ub=bb.next();!ub.done;ub=bb.next())vb=ub.value,tc=g.FC(vb.key).entityId,
tc!==a||B5(c,vb.actionProto)||ba.push(vb.key);return g.A(kb,b5(b,{mode:"readwrite",jc:!0},function(Sb){var Cb=ba.map(function(oe){return Y4(Sb,oe)});
Cb.push(Y4(Sb,qa,{du:!0}));Cb.push(Y4(Sb,fb,{du:!0}));return g.Mr.all(Cb)}),7);
case 7:C5(G),k5(d,{entityKey:qa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),k5(d,{entityKey:fb,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.va(kb)}})},k_a=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,za,ba,qa,fb,bb,ub,vb,tc;
return g.B(function(kb){switch(kb.j){case 1:return e=g.GC(a,"mainPlaylistEntity"),f=g.GC(a,"ytMainChannelEntity"),g.A(kb,b5(b,{mode:"readonly",jc:!0},function(Sb){return g.Mr.all([T4(Sb,e,"mainPlaylistEntity"),T4(Sb,f,"ytMainChannelEntity"),U4(Sb,"mainPlaylistEntity"),U4(Sb,"ytMainChannelEntity"),U4(Sb,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:h=kb.u;l=g.r(h);m=l.next().value;n=l.next().value;p=l.next().value;q=l.next().value;t=l.next().value;u=m;x=n;y=p;z=q;D=t;if(!u&&!x){kb.Ra(3);break}H=u?i_a(u):[];if(!x){G=[];kb.Ra(4);break}return g.A(kb,h_a(x,z),5);case 5:G=kb.u;case 4:return L=G,g.A(kb,u5(H.concat(L)),3);case 3:if(!u){kb.Ra(7);break}return g.A(kb,j_a(u,y),8);case 8:aa=kb.u;if(!aa){kb.Ra(7);break}M=g.r(aa);sa=M.next();case 10:if(sa.done){kb.Ra(7);break}za=sa.value;ba=g.FC(za).entityId;return g.A(kb,D5(ba,b,c,d),11);case 11:sa=
M.next();kb.Ra(10);break;case 7:qa=[];fb=g.r(D);for(bb=fb.next();!bb.done;bb=fb.next())ub=bb.value,vb=g.FC(ub.key).entityId,vb!==a||B5(c,ub.actionProto)||qa.push(ub.key);tc=g.GC(a,"mainPlaylistEntity");return g.A(kb,b5(b,{mode:"readwrite",jc:!0},function(Sb){var Cb=qa.map(function(oe){return Y4(Sb,oe)});
Cb.push(Y4(Sb,tc,{du:!0}));return g.Mr.all(Cb)}),0)}})},E5=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,b5(a,{mode:"readwrite",jc:!0},function(p){var q=U4(p,"transfer"),t=U4(p,"offlineOrchestrationActionWrapperEntity");return g.Mr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=l_a.map(function(L){return yZa(p,L)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D=g.FC(z.actionProto.entityKey).entityType,H="ytMainDownloadedVideoEntity"===D;D="mainVideoEntity"===D;var G="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;B5(b,z.actionProto)||H&&(!H||G)&&D&&(!D||G)||u.push(Y4(p,z.key,{du:!0}))}return g.Mr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())h=f.value,C5(h),l=g.FC(h.key).entityId,m=g.GC(l,"ytMainDownloadedVideoEntity"),k5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,g_a(),0)})},n_a=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,za,ba,qa,fb;
return g.B(function(bb){switch(bb.j){case 1:return e=g.GC(a,"musicTrack"),f=g.GC(a,"musicArtist"),h=g.GC(a,"transfer"),g.A(bb,b5(b,{mode:"readonly",jc:!0},function(ub){return g.Mr.all([T4(ub,e,"musicTrack"),T4(ub,f,"musicArtist"),T4(ub,h,"transfer"),U4(ub,"musicArtist"),U4(ub,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=bb.u;m=g.r(l);n=m.next().value;p=m.next().value;q=m.next().value;t=m.next().value;u=m.next().value;x=n;y=p;z=q;D=t;H=u;if(!x&&!y){bb.Ra(3);break}G=x?A5(x.thumbnailDetails):[];if(!y){L=[];bb.Ra(4);break}return g.A(bb,m_a(y,D),5);case 5:L=bb.u;case 4:return aa=L,g.A(bb,u5(G.concat(aa)),3);case 3:M=[];sa=g.GC(a,"musicTrack");za=g.r(H);for(ba=za.next();!ba.done;ba=za.next())qa=ba.value,fb=g.FC(qa.key).entityId,fb!==a||B5(c,qa.actionProto)||M.push(qa.key);return g.A(bb,b5(b,{mode:"readwrite",
jc:!0},function(ub){var vb=M.map(function(tc){return Y4(ub,tc)});
vb.push(Y4(ub,sa,{du:!0}));return g.Mr.all(vb)}),7);
case 7:C5(z),k5(d,{entityKey:sa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.va(bb)}})},o_a=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,b5(a,{mode:"readwrite",jc:!0},function(p){var q=U4(p,"transfer"),t=U4(p,"offlineOrchestrationActionWrapperEntity");return g.Mr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=l_a.map(function(G){return yZa(p,G)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D="musicTrack"===g.FC(z.actionProto.entityKey).entityType,H="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;B5(b,z.actionProto)||D&&(!D||H)||u.push(Y4(p,z.key,{du:!0}))}return g.Mr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())h=f.value,C5(h),l=g.FC(h.key).entityId,m=g.GC(l,"ytMainDownloadedVideoEntity"),k5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,g_a(),0)})},B5=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},C5=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.FC(a.key).entityId;
m5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,mj:a})}},A5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},i_a=function(a,b){var c=[];
if(a.thumbnailStyleData){a=g.r(a.thumbnailStyleData);for(var d=a.next();!d.done;d=a.next()){var e=void 0,f=void 0,h=void 0;c=c.concat(A5(null==(e=d.value)?void 0:null==(f=e.value)?void 0:null==(h=f.collageThumbnail)?void 0:h.coverThumbnail))}}b=A5(b);return c.concat(b)},j_a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u;
return g.B(function(x){c=[];if(a.videos){d=g.r(a.videos);for(e=d.next();!e.done;e=d.next())f=e.value,c.push(f);h=g.r(b);for(l=h.next();!l.done;l=h.next())if(m=l.value,m.key!==a.key&&(n=m.videos))for(p=g.r(n),q=p.next();!q.done;q=p.next())t=q.value,u=c.indexOf(t),-1!==u&&c.splice(u,1)}return x.return(c)})},h_a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){c=A5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(h=g.r(A5(f.avatar)),l=h.next();!l.done;l=h.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},m_a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){c=A5(a.thumbnailDetails);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(h=g.r(A5(f.thumbnailDetails)),l=h.next();!l.done;l=h.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},F5=function(a){this.j=a},p_a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Ra(4);break}f=e.value;h=c;l=h.set;m=f;return g.A(n,a.u(f),5);case 5:l.call(h,m,n.u);e=d.next();n.Ra(2);break;case 4:return n.return(c)}})},G5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},H5=function(a,b,c){this.j=a;
this.U=b;this.B=c},s_a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.wa(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,q_a(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,iS:q}),4);case 4:return(h=n.u)?g.A(n,r_a(a,h,b),5):n.return(I5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(I5(b,!0,h.orchestrationActions));case 2:return l=g.ya(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Fr&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),i5("PDE handleAdd error"),n.return(I5(b,!1,void 0,m))}})},t_a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){switch(D.j){case 1:return c=b.entityKey,g.A(D,b5(a.j,{mode:"readonly",jc:!0},function(H){var G=T4(H,c,"playbackData"),L=T4(H,g.GC(g.FC(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");H=T4(H,g.GC(g.FC(b.entityKey).entityId,"transfer"),"transfer");return g.Mr.all([G,L,H])}),2);
case 2:d=D.u;e=g.r(d);f=e.next().value;h=e.next().value;l=e.next().value;m=f;n=h;p=l;if(!m||!n)return D.return(I5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(u=p)?0:u.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.wa(D,3);return g.A(D,q_a(a,c,{refreshData:q,iS:t}),5);case 5:return(x=D.u)?g.A(D,r_a(a,x,b),6):D.return(I5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return D.return(I5(b,
!0,x.orchestrationActions));case 3:return y=g.ya(D),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.Fr&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),D.return(I5(b,!1,void 0,z))}})},q_a=function(a,b,c){var d,e,f;
return g.B(function(h){d=g.cI();var l=a.U,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.iS,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.oI(l),signatureTimestamp:19144,videos:[q]};f=g.OH(u_a);return h.return(g.ZF(d,e,f))})},r_a=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Ra(2);d=g.FC(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,D5(d,a.j,c,a.B),2)}return g.A(e,JZa(b.frameworkUpdates.entityBatchUpdate),0)})},I5=function(a,
b,c,d){return new G5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",w5(a),c,d)},J5=function(){F5.apply(this,arguments)},w_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=w5(b),g.A(e,e5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(e,3);return g.A(e,v_a(a,b),5);case 5:g.xa(e,4);break;case 3:return g.ya(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},x_a=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=w5(b),g.A(e,e5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(e,3);return g.A(e,v_a(a,b,!0),5);case 5:g.xa(e,4);break;case 3:return g.ya(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},v_a=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,h,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.Hu(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(h=e)?void 0:h.preferredAudioTrack,transferRetryCount:0,isRefresh:c,hasLoggedFirstStarted:!1},m=g.FC(l.key).entityId,g.A(n,b5(a.j,{mode:"readwrite",jc:!0},function(p){var q=
[];c&&q.push(Y4(p,g.GC(m,"offlineVideoStreams")));q.push(W4(p,l,"transfer"));return g.Mr.all(q)}),2);
m5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,mj:l});g.va(n)})},y_a=function(a,b,c){return new g.mD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},z_a=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},K5=function(a,b,c,d,e,f,h,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=h;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},L5=function(a){return{key:g.GC(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},A_a=function(){this.j=new Map},B_a=function(){M5||(M5=new A_a);
return M5},C_a=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},D_a=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.Hu(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.vr("flowEvent",a,void 0)},E_a=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.FC(a.action.entityKey);a={entityType:d.pW,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},N5=function(a,b){var c={offlineOrchestrationContext:E_a(a)};
b=C_a(b,c);D_a(B_a(),b,a.rootActionId)},O5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:E_a(a,b,c)};b=C_a(3,b);D_a(B_a(),b,a.rootActionId)},F_a=function(){this.actions=[]},G_a=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,N5(c,1),a.actions.push(c);a.actions.sort(a.j)},H_a=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},P5=function(a,b,c,d){g.I.call(this);
var e=this;this.u=a;this.Y=b;this.V=c;this.D=d;this.j=new F_a;this.N=new g.Ns;this.C=new g.K(function(){e.retry()});
this.I=NaN;g.J(this,this.C);this.J=c5(this.u,this.W.bind(this))},J_a=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new P5(a,b,c,d),g.A(f,I_a(e),2);e.B?Promise.resolve():Q5(e);return f.return(e)})},Q5=function(a){var b,c,d,e,f,h,l,m,n,p,q,t,u,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();a_a(a.V,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.Y[b.entityType]){z.Ra(2);break}a.B=void 0;return g.A(z,Q5(a),3);case 3:return z.return();case 2:f=g.r(c);for(h=f.next();!h.done;h=f.next())l=h.value,N5(l,2);g.wa(z,4,
5);return g.A(z,p_a(e,c.map(function(D){return D.action})),7);
case 7:m=z.u,n=g.r(c),h=n.next();case 8:if(h.done){z.Ra(5);break}p=h.value;q=m.get(p.action);return g.A(z,K_a(a,p,q),9);case 9:h=n.next();z.Ra(8);break;case 5:g.Aa(z);a.B=void 0;g.Ba(z,6);break;case 4:return t=g.ya(z),i5("Orchestration error",t),g.wa(z,12),g.A(z,L_a(a,c),14);case 14:g.xa(z,5);break;case 12:u=g.ya(z);i5("Orchestration retry error",u);x=g.r(c);for(h=x.next();!h.done;h=x.next())y=h.value,3>y.retryScheduleIndex&&G_a(a.j,[y]);z.Ra(5);break;case 6:return g.A(z,Q5(a),0)}})},K_a=function(a,
b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){h=void 0;try{h=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return O5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},k5(a.D,m),i5("Orchestration subactions creation error",p),n.return()}O5(b,c,h);return g.A(n,b5(a.u,{mode:"readwrite",jc:!0},function(p){var q=[];if(h){var t=h.map(function(u){return L5(u)});
q.push(X4(p,t,"offlineOrchestrationActionWrapperEntity"))}t=L5(b);q.push(Y4(p,t.key));return g.Mr.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Ra(0);
O5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,L_a(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};k5(a.D,f);i5("Orchestration result is not retryable, deleting action");return g.A(n,FZa(a.u,L5(b).key),0)}N5(b,4);g.va(n)})},R5=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(h=f.next();!h.done;h=f.next())l=h.value,m=Number(l.enqueueTimeSec),n=M_a(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.I)&&(a.I=d,a.C.start(e));a.N.tf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!N_a.includes(y)}),u=c.length<t,!a.C.isActive()&&u&&a.C.start(1));
0<c.length&&O_a(a,c);return g.A(x,a.B?Promise.resolve():Q5(a),0)})},Q_a=function(a){var b,c,d,e,f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,P_a(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,h=g.FC(f.key),l=h.entityId,H_a(a.j,l)||c.push(f);return g.A(m,R5(a,c),0)})},M_a=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},L_a=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var h=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(h=l.actionMetadata)?void 0:h.retryScheduleIntervalsInSeconds)||[1,2,4];h=1;e.retryScheduleIndex<m.length&&(h=m[e.retryScheduleIndex]);e.j=1E3*h+Date.now();e.retryScheduleIndex++}return g.A(f,R_a(a,b),0)})},I_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,f5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,R5(a,b),0)})},O_a=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.FC(c.key),e=g.FC(c.actionProto.entityKey);c=new K5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&G_a(a.j,[c])})},P_a=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,f5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(KZa))})},R_a=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return L5(c)});
return EZa(a.u,b)},S_a=function(){this.j=void 0},U_a=function(a,b){var c,d,e,f,h;
return g.B(function(l){c=b.videoId;d=b.S();e=!0;if(b.captionTracks.length)f=jZa(b),a.j=new g.$I(d,b,f);else if(b.Jc)h=g.Zxa(b),a.j=new g.bJ(d,b.Jc,c,h,b.yl),e=b.yl;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.hv(function(){return g.B(function(p){if(1==p.j)return g.A(p,T_a(a,c,e),2);m();g.va(p)})})}))})},T_a=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,h,l,m,n,p,q,t,u,x,y,z;return g.B(function(D){switch(D.j){case 1:if(!a.j)return D.return();d=[];e=g.XI(a.j.u,c);f=[];h={};l=g.r(e.entries());for(m=l.next();!m.done;h={UD:h.UD},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,h.UD=q,u=t,x=a.j.Dr(u,"json3"),y=g.sq(x,{withCredentials:!0,format:"RAW"},3,500).then(function(H){return function(G){G={metadata:g.YC(e[H.UD]),trackData:G.xhr.responseText};f.push(G)}}(h)).Li(function(H){i5("Caption fetch error",H)}),d.push(y);
return g.A(D,kZa(d),2);case 2:return g.wa(D,3),g.A(D,OZa(b,f),5);case 5:g.xa(D,0);break;case 3:z=g.ya(D),i5("Caption DB transaction error",z),g.va(D)}})},V_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,PZa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},W_a=function(a,b){this.api=a;
this.j=b;this.logger=new g.qO("woffle");this.u=!1},X_a=function(a){return g.B(function(b){return b.return(QZa(a))})},Y_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Kwa(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},S5=function(a,b){var c=g.RC(b);
if(1===c||0===c)return Promise.resolve();(c=Z_a(a,b))&&c.stopVideo();a.B=0;return X_a(b)},T5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.RC(e)&&((b=Z_a(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.SC(e,2),a.B=2,c?$_a(a.j):d&&a0a(a.j))},Z_a=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},b0a=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},U5=function(a){g.I.call(this);
this.j=a;this.u=c5(this.j,this.B.bind(this))},c0a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.GC(p,"transfer")});
return g.A(n,f5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(KZa).map(function(p){return g.FC(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);h=g.r(f);l=h.next();case 3:if(l.done){n.Ra(5);break}m=l.value;return g.A(n,X_a(m),4);case 4:l=h.next();n.Ra(3);break;case 5:return n.return(f)}})},e0a=function(a,b,c,d,e,f){var h,l,m;
return g.B(function(n){h="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(h="STREAM_TYPE_AUDIO_AND_VIDEO",i5("unexpected stream type")):c.video&&!c.audio?h="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(h="STREAM_TYPE_AUDIO");l=g.GC(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:h,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===h?Number(c.Vb()):void 0};return g.A(n,b5(a,{mode:"readwrite",jc:!0},
function(p){var q=T4(p,l,"offlineVideoStreams"),t=T4(p,g.GC(b,"transfer"),"transfer");return g.Mr.all([q,t]).then(function(u){var x=g.r(u);u=x.next().value;x=x.next().value;if(!x)return Y4(p,l).then(function(){});
u=[W4(p,d0a(u,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),u.push(W4(p,x,"transfer")));return g.Mr.all(u)})}),0)})},f0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){if(1==l.j)return c=g.GC(b,"offlineVideoStreams"),g.A(l,e5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())h=f.value,h.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",h.numTotalBytes!==h.numBytesDownloaded&&(h.numBytesDownloaded=h.numTotalBytes);return g.A(l,d5(a,d,"offlineVideoStreams"),0)})},d0a=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var h=JSON.parse(e[f].formatStreamBytes);if(h.itag+";"+h.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},V5=function(a,b,c,d){g.I.call(this);
var e=this;this.u=a;this.api=b;this.va=c;this.ma=d;this.D=new g.Ns;this.C=new g.K(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.tf()&&(3>(e.j.transferRetryCount||0)?T5(e.I,e.B,!1,!1):S5(e.I,e.B.videoDetails.videoId),e.qs("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.V=0;this.oa=new g.kz(this);this.J=c5(this.u,this.VS.bind(this));this.I=new W_a(b,this);this.Ga=new S_a;this.N=new U5(this.u);this.Y=this.D.Ma("publicytnetworkstatus-online",this.xz.bind(this));this.W=this.D.Ma("publicytnetworkstatus-offline",this.q0.bind(this));g.J(this,this.oa);this.oa.P(b,"offlinetransferpause",this.r0);this.Da=g.eA(this.api.S().experiments,"web_player_transfer_timeout_threshold_ms")},g0a=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,NZa(),2);
else{var c=a.N;var d=g.QC();d=Object.keys(d);c=c0a(c,d);b=g.A(b,c,0)}return b})},X5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,h0a(a),2)}return 4!=d.j?(c=d.u,b_a(a.va,!c),c&&a.D.tf()?b?g.A(d,new Promise(function(e){g.kq(e,1E3)}),4):d.Ra(4):(!c&&a.j&&W5(a),d.Ra(0))):g.A(d,i0a(a,c),0)})},j0a=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,S5(a.I,a.B.videoDetails.videoId),3):b.Ra(0);
W5(a);g.va(b)})},k0a=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.wa(f,2),(c=!!b.captionTracks.length||!!b.Jc)?g.A(f,V_a(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,U_a(a.Ga,b),5);case 5:g.xa(f,0);break;case 2:e=g.ya(f),i5("Caption downloading error",e,b.cotn),g.va(f)}})},i0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.FC(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&m5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,mj:a.j}),g.A(l,Y5(a),2);case 2:return d=null,g.wa(l,3),g.A(l,l0a(a,b),5);case 5:d=l.u;a.B=d;g.xa(l,4);break;case 3:return e=g.ya(l),i5("error getting player response",e,b.cotn),g.A(l,a.qs("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
y_a(a.api.S(),b.cotn,d),g.A(l,k0a(a,f),7);case 7:return h=f,g.A(l,Y_a(f.videoId),8);case 8:h.Xm=l.u;var m=a.I,n=b.maximumDownloadQuality;f.getPlayerResponse();g.SC(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.Yo(9,f);p={};g.ju(m.player,(p.localmediachange=m.EC,p.signatureexpired=m.rI,p.statechange=m.fZ,p),m);n=b0a(n);m.K("hoffle_lmqf_killswitch")||g.hNa(m.player,g.Mw(n,n,!0,"m"),!1);g.FN(m.player,!1);Z5(a);g.va(l)}})},h0a=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,f5(a.u,"transfer"),2);b=d.u;c=b.filter(m0a).sort(n0a);return 0===c.length?d.return():d.return(c[0])})},Y5=function(a){return g.B(function(b){Z5(a);
return g.A(b,$5(a,"TRANSFER_STATE_TRANSFERRING"),0)})},$_a=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,$5(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.FC(a.j.key);d_a({videoId:b.entityId,mj:a.j});W5(a);X5(a);g.va(c)})},a0a=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,$5(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
W5(a);g.va(b)})},o0a=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Ra(2);break}b=y_a(a.api.S(),a.j.cotn,a.B);return g.A(e,k0a(a,b),2);case 2:return g.A(e,$5(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.FC(a.j.key),d=c.entityId,g.A(e,f0a(a.u,d),5);case 5:m5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,mj:a.j}),W5(a),X5(a),g.va(e)}})},q0a=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Ra(2);break}return g.A(e,Y5(a),2);case 2:d=Date.now();if(!(1E3<d-a.V)){e.Ra(4);break}a.V=d;return g.A(e,e0a(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:if(a.j.hasLoggedFirstStarted){c_a({videoId:b,mj:a.j},c.bytesDownloaded,c.j);e.Ra(4);break}a.j.hasLoggedFirstStarted=!0;return g.A(e,p0a(a),7);case 7:c_a({videoId:b,mj:a.j},c.bytesDownloaded,c.j,!0);case 4:Z5(a),g.va(e)}})},r0a=function(a){var b=
3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},s0a=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,$5(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);k5(a.ma,{entityKey:a.j.key,failureReason:c});d=g.FC(a.j.key).entityId;var f={videoId:d,mj:a.j},h=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};h&&(l.transferFailureReason=h,l.failureReason=e_a(h));m5(l,f);g.va(e)})},$5=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.wa(f,2),g.A(f,p0a(a,function(h){return c?U4(h,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return X4(h,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.Mr.resolve(void 0)}),4);
if(2!=f.j)return g.xa(f,0);e=g.ya(f);return e instanceof g.Fr&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.qs("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Ra(0)})},p0a=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,b5(a.u,{mode:"readwrite",jc:!0},function(e){var f=[W4(e,c,"transfer")];b&&f.push(b(e));return g.Mr.all(f)}),0)})},W5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},l0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){if(1==l.j)return c=g.FC(b.key),d=c.entityId,e=g.GC(d,"playbackData"),g.A(l,e5(a.u,e,"playbackData"),2);f=l.u;if(null==(h=f)?0:h.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},Z5=function(a){a.C.start(a.Da||18E5)},m0a=function(a){return void 0!==a6[a.transferState]},n0a=function(a,b){var c=a6[a.transferState],d=a6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},b6=function(a,b){var c=this;
this.U=a;this.api=b;this.N=new g.Ns;this.B=new YZa(function(){return t0a(c)},function(){u0a(c)},this.api.Cp(),this.api.K.bind(this.api));
this.u=new j5(this.api);this.C=new g.qi;ZZa(this.B)},t0a=function(a){return g.B(function(b){a.api.La("onOrchestrationBecameLeader");
a.j&&a.D||v0a(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},v0a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,h5(),2);if(3!=e.j){b=e.u;if(!b)return i5("PES is undefined"),e.return();a.j=new V5(b,a.api,a.B,a.u);c=a.Px(b);d=a;return g.A(e,J_a(b,c,a.B,a.u),3)}d.D=e.u;return g.A(e,w0a(a),0)})},w0a=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return i5("transferManager is undefined"),c.return();if(a.j.j){c.Ra(2);break}return g.A(c,X5(a.j),2);case 2:return g.A(c,a.rz(),4);case 4:return a.J=g.lq(function(){a.rz()},9E5),g.lr(g.nr(),function(){return a.jJ()}),g.A(c,h5(),5);
case 5:return b=c.u,g.A(c,UZa(b),6);case 6:$Za(a.B),g.va(c)}})},u0a=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(window.clearInterval(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.La("onOrchestrationLostLeader");a.C=new g.qi;g.va(d)})},x0a=function(){var a,b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return g.A(h,h5(),2);case 2:a=h.u;if(!a)return h.return([]);b=Date.now()/1E3;return g.A(h,f5(a,"offlineVideoPolicy"),3);case 3:c=h.u,d=g.r(c),e=d.next();case 4:if(e.done){h.Ra(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){h.Ra(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(h,d5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();h.Ra(4);break;case 6:return h.return(c.map(function(l){return l.key}))}})},c6=
function(a,b,c,d,e){var f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,h5(),2);f=m.u;if(!f)return m.return([]);h=b.map(function(n){var p=g.GC(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},z_a(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new K5(c,n,p);return L5(n)});
l=EZa(f,h);ZZa(a.B);return m.return(l)})},d6=function(a){var b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return b=g.cI(),c=RZa(a),d=g.OH(y0a),g.wa(h,2),g.A(h,g.ZF(b,c,d),4);case 4:e=h.u;g.xa(h,3);break;case 2:throw f=g.ya(h),i5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return h.return(e.videos.map(function(l){return l.offlineVideoData}))}})},z0a=function(a){var b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return b=g.cI(),c=SZa(a),d=g.OH(y0a),g.wa(h,2),g.A(h,g.ZF(b,c,d),4);case 4:e=h.u;g.xa(h,3);break;case 2:throw f=g.ya(h),i5("GetOffline fetch request error for playlist",f),Error("GetOffline fetch request error for playlist");case 3:if(!e)throw Error("Network request failed");if(!e.playlists||!e.playlists.length)throw Error("No data");return h.return(e.playlists.map(function(l){return l.offlinePlaylistData}))}})},e6=function(a,b,c){this.j=a;
this.U=b;this.B=c},C0a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u,x;
return g.B(function(y){switch(y.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,f=[],g.wa(y,2),g.A(y,A0a(a,e),4);case 4:f=y.u;g.xa(y,3);break;case 2:return h=g.ya(y),l="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",h instanceof g.Fr&&"QUOTA_EXCEEDED"===h.type&&(l="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),y.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,l));case 3:m=[];if(null==(n=f)?0:n.length)for(p=g.r(f),q=p.next();!q.done;q=p.next())if(t=q.value,u=
t.offlineVideoData,x=void 0,null==(x=u)?0:x.videoId){var z=m,D=z.push,H=void 0,G={offlineVideoData:u};if(null==(H=b.actionMetadata)?0:H.mainPlaylistEntityActionMetadata)G.maximumDownloadQuality=b.actionMetadata.mainPlaylistEntityActionMetadata.maximumDownloadQuality;G={mainVideoEntityActionMetadata:G};H=g.GC(u.videoId,"mainVideoEntity");G=Object.assign({},G,{priority:0,retryScheduleIntervalsInSeconds:B0a});D.call(z,{actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",entityKey:H,actionMetadata:G})}return y.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c,m))}})},D0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=w5(b),g.wa(e,2),d=g.FC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,E5(a.j,b,a.B),5):g.A(e,k_a(d,a.j,b,a.B),5);case 5:g.xa(e,3);break;case 2:return g.ya(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},A0a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return g.A(m,z0a([b]),2);case 2:return c=m.u,g.A(m,E0a(a,c[0]),3);case 3:return d=m.u,e=d.mainPlaylistEntity,f=d.v0,g.wa(m,4),h=i_a(e,f.avatar),g.A(m,v5(h),6);case 6:g.xa(m,5);break;case 4:if(l=g.ya(m),!a.U.K("woffle_disable_thumbnails"))throw l;case 5:return m.return(c[0].videos)}})},E0a=function(a,b){var c=void 0,d,e,f,h,l,m,n,p,q,t,u,x,y;
return g.B(function(z){if(1==z.j){if(!(b&&b.playlistId&&b.channel&&b.channel.offlineChannelData))throw Error("Invalid OfflinePlaylistData");c||(c=Date.now().toString());d=b.videos;e=[];f=[];if(d)for(h=g.r(d),l=h.next();!l.done;l=h.next()){m=l.value;n=m.offlineVideoData;if(!n||!n.videoId)throw Error("Invalid offlineVideoData");p=n.videoId;q={id:g.GC(p,"mainPlaylistVideoEntity"),video:g.GC(p,"mainVideoEntity")};e.push(q);f.push(q.id)}t=b.playlistId;u=b.channel.offlineChannelData;x=F0a(g.GC(t,"ytMainChannelEntity"),
u);y={key:g.GC(t,"mainPlaylistEntity"),playlistId:t,channelOwner:x.id,videos:f,title:b.title,thumbnailStyleData:G0a(b),visibility:H0a(b)};return g.A(z,b5(a.j,{mode:"readwrite",jc:!0},function(D){for(var H=W4(D,y,"mainPlaylistEntity"),G=W4(D,x,"ytMainChannelEntity"),L=[],aa=g.r(e),M=aa.next();!M.done;M=aa.next())L.push(W4(D,M.value,"mainPlaylistVideoEntity"));return g.Mr.all([H,G].concat(g.v(L)))}),2)}return z.return({mainPlaylistEntity:y,
v0:x,Eka:e})})},F0a=function(a,b){if(!(b.channelId&&b.title&&b.thumbnail))throw Error("Invalid OfflineChannelData");
return{id:a,channelId:b.channelId,title:b.title,avatar:b.thumbnail}},G0a=function(a){var b=[],c=a.videos;
c&&0<c.length&&b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_FIRST_VIDEO"),value:{collageThumbnail:{coverThumbnail:c[0].offlineVideoData.thumbnail}}});if((a=a.additionalMetadadatas)&&0<a.length)for(a=g.r(a),c=a.next();!c.done;c=a.next()){var d=c.value.offlineBundleItemPlaylistData,e=void 0;c=null==(e=d)?void 0:e.style;e=void 0;d={collageThumbnail:{coverThumbnail:null==(e=d)?void 0:e.coverThumbnail}};switch(c){case "BUNDLE_ITEM_STYLE_UNSPECIFIED":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_UNKNOWN"),
value:d});break;case "BUNDLE_ITEM_STYLE_TWO_BY_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_TWO_BY_TWO"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO_AVATAR":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO_AVATAR"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO"),value:d})}}return b},H0a=function(a){switch(a.privacy){case "PRIVATE":return"PLAYLIST_VISIBILITY_PRIVATE";
case "PUBLIC":return"PLAYLIST_VISIBILITY_PUBLIC";case "UNLISTED":return"PLAYLIST_VISIBILITY_UNLISTED";default:return"PLAYLIST_VISIBILITY_UNKNOWN"}},f6=function(a,b,c){this.j=a;
this.U=b;this.B=c},K0a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){switch(p.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,g.wa(p,2),g.A(p,I0a(a,e,void 0,null==(f=b.actionMetadata)?void 0:null==(h=f.mainVideoEntityActionMetadata)?void 0:h.offlineVideoData),4);case 4:g.xa(p,3);break;case 2:return l=g.ya(p),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Fr&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),p.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m));
case 3:var q;var t=null!=(q=b.actionMetadata)&&q.mainVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.mainVideoEntityActionMetadata.maximumDownloadQuality}}:void 0;n=J0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,t);return p.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[n]))}})},L0a=function(a,b){var c,d,e,f,h,l,m,n,p;
return g.B(function(q){switch(q.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,g.A(q,e5(a.j,b.entityKey,"mainVideoEntity"),2);case 2:f=q.u;if(!f){h=void 0;q.Ra(3);break}return g.A(q,e5(a.j,f.downloadState,"mainVideoDownloadStateEntity"),4);case 4:h=q.u;case 3:l=h;if(!f||!l)return q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(q,5);return g.A(q,I0a(a,e,l.addedTimestampMillis),7);case 7:m=J0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.xa(q,6);break;case 5:return n=
g.ya(q),n instanceof Error&&"No data"===n.message?g.A(q,D5(e,a.j,b,a.B),6):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.Fr&&"QUOTA_EXCEEDED"===n.type&&(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 6:return q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},M0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=w5(b),g.wa(e,2),d=g.FC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,E5(a.j,b,a.B),5):g.A(e,D5(d,a.j,b,a.B),5);case 5:g.xa(e,3);break;case 2:return g.ya(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},I0a=function(a,b,c,d){var e,f,h,l,m,n;
return g.B(function(p){switch(p.j){case 1:if(e=d){p.Ra(2);break}return g.A(p,d6([b]),3);case 3:f=p.u,e=f[0];case 2:return g.A(p,N0a(a,e,c),4);case 4:h=p.u;l=h.mainVideoEntity;m=h.channelEntity;g.wa(p,5);var q=A5(l.thumbnail),t=A5(m.avatar);return g.A(p,v5(q.concat(t)),7);case 7:g.xa(p,0);break;case 5:n=g.ya(p);if(!a.U.K("woffle_disable_thumbnails"))throw n;g.va(p)}})},N0a=function(a,b,c){var d,e,f,h,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.GC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};h={key:g.GC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.GC(b.videoId,"playbackData"),addedTimestampMillis:c};l={key:g.GC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,
thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:h.key};return g.A(m,b5(a.j,{mode:"readwrite",jc:!0},function(n){var p=W4(n,f,"ytMainChannelEntity"),q=W4(n,h,"mainVideoDownloadStateEntity");n=W4(n,l,"mainVideoEntity");return g.Mr.all([p,q,n])}),2)}return m.return({mainVideoEntity:l,
channelEntity:f})})},J0a=function(a,b,c){b=g.GC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:O0a});return{actionType:a,entityKey:b,actionMetadata:c}},g6=function(a,b,c){this.j=a;
this.U=b;this.B=c},R0a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,g.wa(m,2),g.A(m,P0a(a,e),4);case 4:g.xa(m,3);break;case 2:return f=g.ya(m),h="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Fr&&"QUOTA_EXCEEDED"===f.type&&(h="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,h));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=Q0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},S0a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,g.A(n,e5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(n,3);return g.A(n,P0a(a,e,f.addedTimestampMillis),5);case 5:h=Q0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.xa(n,4);break;case 3:return l=g.ya(n),l instanceof Error&&"No data"===l.message?g.A(n,D5(e,a.j,b,a.B),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.Fr&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,h?[h]:void 0))}})},T0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=w5(b),g.wa(e,2),d=g.FC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,E5(a.j,b,a.B),5):g.A(e,D5(d,a.j,b,a.B),5);case 5:g.xa(e,3);break;case 2:return g.ya(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},P0a=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,d6([b]),2);case 2:return d=n.u,e=d[0],g.A(n,U0a(a,e,c),3);case 3:f=n.u;h=f.videoEntity;l=f.channelEntity;g.wa(n,4);var p=A5(h.thumbnail),q=A5(l.avatar);return g.A(n,v5(p.concat(q)),6);case 6:g.xa(n,0);break;case 4:m=g.ya(n);if(!a.U.K("woffle_disable_thumbnails"))throw m;g.va(n)}})},U0a=function(a,b,c){var d,e,f,h,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.GC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};h={id:g.GC(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.GC(b.videoId,"ytMainDownloadedVideoEntity"),video:h.id,playbackData:g.GC(b.videoId,"playbackData"),offlineVideoPolicy:g.GC(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.U.K("woffle_entity_migration")?(m={key:g.GC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.GC(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.GC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,b5(a.j,{mode:"readwrite",jc:!0},function(q){var t=W4(q,f,"ytMainChannelEntity"),u=W4(q,h,"ytMainVideoEntity"),x=W4(q,l,"ytMainDownloadedVideoEntity"),
y=W4(q,m,"mainVideoDownloadStateEntity");q=W4(q,n,"mainVideoEntity");return g.Mr.all([t,u,x,y,q])}),3)):g.A(p,b5(a.j,{mode:"readwrite",
jc:!0},function(q){var t=W4(q,f,"ytMainChannelEntity"),u=W4(q,h,"ytMainVideoEntity");q=W4(q,l,"ytMainDownloadedVideoEntity");return g.Mr.all([t,u,q])}),3)}return p.return({videoEntity:h,
channelEntity:f,Sja:l})})},Q0a=function(a,b,c){b=g.GC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:V0a});return{actionType:a,entityKey:b,actionMetadata:c}},h6=function(){b6.apply(this,arguments);
this.I="ytMainDownloadedVideoEntity"},W0a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,h5(),2):(a=b.u)?g.A(b,b5(a,{mode:"readwrite",jc:!0},function(c){var d=U4(c,"ytMainDownloadedVideoEntity"),e=U4(c,"ytMainVideoEntity"),f=U4(c,"mainVideoEntity");return g.Mr.all([d,e,f]).then(function(h){h=g.r(h);var l=h.next().value,m=h.next().value,n=h.next().value;h={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.FC(p.id).entityId;h[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.FC(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.FC(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(h));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=h[q],u=l[q];t={key:g.GC(q,"mainVideoDownloadStateEntity"),playbackData:g.GC(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.GC(q,"mainVideoEntity"),videoId:q,title:u.title,thumbnail:u.thumbnail,localizedStrings:u.localizedStrings,lengthSeconds:u.lengthSeconds,publishedTimestampMillis:u.publishedTimestampMillis,
formattedDescription:u.formattedDescription,owner:u.channelOwner,downloadState:t.key},t];n.push(W4(c,q[0],"mainVideoEntity"),W4(c,q[1],"mainVideoDownloadStateEntity"))}return g.Mr.all(n)})}),0):b.return()})},i6=function(a,b,c){this.j=a;
this.U=b;this.B=c},Z0a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,g.wa(m,2),g.A(m,X0a(a,e),4);case 4:g.xa(m,3);break;case 2:return f=g.ya(m),h="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Fr&&"QUOTA_EXCEEDED"===f.type&&(h="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,h));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.musicTrackEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.musicTrackEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=Y0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},$0a=function(a,b){var c,d,e,f,h,l,m,n,p;
return g.B(function(q){switch(q.j){case 1:return c=w5(b),d=g.FC(b.entityKey),e=d.entityId,g.A(q,e5(a.j,b.entityKey,"musicTrack"),2);case 2:f=q.u;if(!f){h=void 0;q.Ra(3);break}return g.A(q,e5(a.j,f.downloadMetadata,"musicTrackDownloadMetadataEntity"),4);case 4:h=q.u;case 3:l=h;if(!f||!l)return q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(q,5);return g.A(q,X0a(a,e,l.addedTimestampMillis),7);case 7:m=Y0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.xa(q,6);break;case 5:return n=
g.ya(q),n instanceof Error&&"No data"===n.message?g.A(q,n_a(e,a.j,b,a.B),6):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.Fr&&"QUOTA_EXCEEDED"===n.type&&(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 6:return q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},a1a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=w5(b),g.wa(e,2),d=g.FC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,o_a(a.j,b,a.B),5):g.A(e,n_a(d,a.j,b,a.B),5);case 5:g.xa(e,3);break;case 2:return g.ya(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},X0a=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,d6([b]),2);case 2:return d=n.u,e=d[0],g.A(n,b1a(a,e,c),3);case 3:f=n.u;h=f.musicTrackEntity;l=f.musicArtistEntity;g.wa(n,4);var p=A5(h.thumbnailDetails),q=A5(l.thumbnailDetails);return g.A(n,v5(p.concat(q)),6);case 6:g.xa(n,0);break;case 4:m=g.ya(n);if(!a.U.K("woffle_disable_thumbnails"))throw m;g.va(n)}})},b1a=function(a,b,c){var d,e,f,h,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){if(1==D.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId&&b.additionalMetadatas))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=g.r(b.additionalMetadatas);for(f=e.next();!f.done;f=e.next())h=f.value,h.offlineMusicVideoData&&(d=h.offlineMusicVideoData);if(!d)throw Error("Invalid OfflineMusicVideoData");m=null==(l=b.channel)?void 0:l.offlineChannelData;n={id:g.GC(b.videoId,"musicArtist"),externalChannelId:m.channelId,name:m.title,thumbnailDetails:m.thumbnail};
p={id:g.GC(b.videoId,"musicTrackDownloadMetadataEntity"),playbackData:g.GC(b.videoId,"playbackData"),addedTimestampMillis:c};z={id:g.GC(b.videoId,"musicTrack"),videoId:b.videoId,title:b.title,thumbnailDetails:b.thumbnail,lengthMs:String(1E3*Number(b.lengthSeconds)),albumTitle:null==(q=d)?void 0:q.releaseTitle,musicVideoType:null==(t=d)?void 0:t.musicVideoType,contentRating:{explicitType:null==(u=d)?void 0:u.explicitType},artists:[n.id],artistNames:(null==(x=d)?void 0:x.byline)||(null==(y=d)?void 0:
y.channelName),downloadMetadata:p.id};return g.A(D,b5(a.j,{mode:"readwrite",jc:!0},function(H){var G=W4(H,n,"musicArtist"),L=W4(H,p,"musicTrackDownloadMetadataEntity");H=W4(H,z,"musicTrack");return g.Mr.all([G,L,H])}),2)}return D.return({musicTrackEntity:z,
musicArtistEntity:n})})},Y0a=function(a,b,c){b=g.GC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:c1a});return{actionType:a,entityKey:b,actionMetadata:c}},j6=function(){b6.apply(this,arguments);
this.I="musicTrack"},k6=function(){g.WI.apply(this,arguments)};
g.w(M3,L3);g.ha.Object.defineProperties(M3.prototype,{entityMetadata:{configurable:!0,enumerable:!0,get:function(){return this.j.entityMetadata},
set:function(a){this.j.entityMetadata=a}}});
g.w(N3,M3);N3.prototype.u=function(){return[]};
g.w(O3,M3);O3.prototype.u=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.v(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.v(new Set(a)))};
g.w(P3,M3);P3.prototype.u=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.v(new Set(a)))};
g.w(Q3,L3);Q3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.v(new Set(a)))};
g.w(R3,M3);R3.prototype.u=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new Q3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(S3,M3);S3.prototype.u=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.v(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.v(new Set(a)))};
g.w(T3,M3);T3.prototype.u=function(){return[]};
g.w(U3,M3);U3.prototype.u=function(){return[]};
g.w(V3,M3);V3.prototype.u=function(){return[]};
g.w(W3,M3);W3.prototype.u=function(){return[]};
g.w(X3,M3);X3.prototype.u=function(){return[]};
g.w(Y3,L3);Y3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playlist&&a.push(this.j.playlist);this.j.videoItem&&a.push(this.j.videoItem);return[].concat(g.v(new Set(a)))};
g.w(Z3,M3);Z3.prototype.u=function(){var a=[];this.j.refresh&&a.push(this.j.refresh);if(this.j.downloads)for(var b=g.r(this.j.downloads),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new Y3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w($3,M3);$3.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(a4,M3);a4.prototype.u=function(){return[]};
g.w(b4,M3);b4.prototype.u=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.v(this.j.fakeChildren));return[].concat(g.v(new Set(a)))};
g.w(c4,M3);c4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(d4,M3);d4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.videos&&a.push.apply(a,g.v(this.j.videos));this.j.collaboratorChannels&&a.push.apply(a,g.v(this.j.collaboratorChannels));return[].concat(g.v(new Set(a)))};
g.w(e4,M3);e4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.channelContributor&&a.push(this.j.channelContributor);return[].concat(g.v(new Set(a)))};
g.w(f4,L3);f4.prototype.u=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.v(new Set(a)))};
g.w(g4,M3);g4.prototype.u=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.v((new f4(this.j.userState)).u()));return[].concat(g.v(new Set(a)))};
g.w(h4,M3);h4.prototype.u=function(){return[]};
g.w(i4,M3);i4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.v(new Set(a)))};
g.w(j4,M3);j4.prototype.u=function(){return[]};
g.w(k4,M3);k4.prototype.u=function(){return[]};
g.w(l4,M3);l4.prototype.u=function(){return[]};
g.w(m4,M3);m4.prototype.u=function(){var a=[];this.j.trackDownloadMetadatas&&a.push.apply(a,g.v(this.j.trackDownloadMetadatas));return[].concat(g.v(new Set(a)))};
g.w(n4,M3);n4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(o4,M3);o4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.primaryArtists&&a.push.apply(a,g.v(this.j.primaryArtists));this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));this.j.share&&a.push(this.j.share);this.j.downloadMetadata&&a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(p4,M3);p4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));return[].concat(g.v(new Set(a)))};
g.w(q4,M3);q4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);return[].concat(g.v(new Set(a)))};
g.w(r4,M3);r4.prototype.u=function(){var a=[];this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);return[].concat(g.v(new Set(a)))};
g.w(s4,M3);s4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(t4,M3);t4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(u4,M3);u4.prototype.u=function(){return[]};
g.w(v4,M3);v4.prototype.u=function(){return[]};
g.w(w4,M3);w4.prototype.u=function(){return[]};
g.w(x4,M3);
x4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.artists&&a.push.apply(a,g.v(this.j.artists));this.j.audioModeVersion&&a.push(this.j.audioModeVersion);this.j.videoModeVersion&&a.push(this.j.videoModeVersion);this.j.userDetails&&a.push(this.j.userDetails);this.j.details&&a.push(this.j.details);this.j.albumRelease&&a.push(this.j.albumRelease);this.j.share&&a.push(this.j.share);this.j.libraryEdit&&a.push(this.j.libraryEdit);this.j.downloadMetadata&&
a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(y4,M3);y4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(z4,M3);z4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(A4,M3);A4.prototype.u=function(){return[]};
g.w(B4,M3);B4.prototype.u=function(){return[]};
g.w(C4,M3);C4.prototype.u=function(){return[]};
g.w(D4,M3);D4.prototype.u=function(){return[]};
g.w(E4,M3);E4.prototype.u=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.v(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(F4,M3);F4.prototype.u=function(){return[]};
g.w(G4,M3);G4.prototype.u=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.v(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.v(this.j.captionTrack));return[].concat(g.v(new Set(a)))};
g.w(H4,M3);H4.prototype.u=function(){return[]};
g.w(I4,M3);I4.prototype.u=function(){return[]};
g.w(J4,M3);J4.prototype.u=function(){return[]};
g.w(K4,M3);K4.prototype.u=function(){return[]};
g.w(L4,M3);L4.prototype.u=function(){return[]};
var y0a=["offline"],u_a=["offline/get_playback_data_entity"],N4;g.w(O4,g.Ar);g.w(Q4,rZa);Q4.prototype.B=function(a,b){b=P4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
Q4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw nZa(1);var c=new TextDecoder;b=P4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
var tZa={buttonEntity:H4,captionTrack:A4,channelHandle:N3,commerceCartListEntity:J4,downloadQualityPickerEntity:W3,downloadsPageRefreshTokenEntity:X3,downloadsPageViewConfigurationEntity:j4,fakeChannel:O3,fakePlaylist:P3,fakePlaylistEntryCollection:R3,fakeVideo:S3,fakeVideoDescription:T3,iconBadgeEntity:K4,liveChatPollStateEntity:V3,logoEntity:U3,mainDownloadsListEntity:Z3,mainPlaylistEntity:d4,mainPlaylistVideoEntity:e4,mainVideoDownloadStateEntity:$3,mainVideoEntity:g4,markersVisibilityOverrideEntity:k4,
musicAlbumReleaseDetail:p4,musicAlbumReleaseDownloadMetadataEntity:m4,musicAlbumRelease:o4,musicAlbumReleaseUserDetail:q4,musicArtistDetail:s4,musicArtist:r4,musicArtistUserDetail:t4,musicLibraryEdit:u4,musicLibraryStatusEntity:v4,musicShare:w4,musicTrackDetail:y4,musicTrackDownloadMetadataEntity:n4,musicTrack:x4,musicTrackUserDetail:z4,offlineOrchestrationActionWrapperEntity:B4,offlineVideoPolicy:C4,offlineVideoStreams:D4,offlineabilityEntity:a4,orchestrationWebSamplingEntity:b4,pinnedProductEntity:l4,
playbackData:E4,quantityIncrementerEntity:L4,refresh:F4,transfer:G4,videoPlaybackPositionEntity:I4,ytMainChannelEntity:h4,ytMainDownloadedVideoEntity:c4,ytMainVideoEntity:i4};g.w($4,rZa);$4.prototype.B=function(a){return a};
$4.prototype.u=function(a){if(a instanceof Uint8Array)throw nZa(0);return a};
g.w(a5,g.I);a5.prototype.B=function(a){DZa(this,a.data)};
a5.prototype.ea=function(){this.channel.close()};
var g5,d1a={N3:"captionTrack",v7:"ytMainDownloadedVideoEntity",w7:"ytMainVideoEntity",paa:"ytMainChannelEntity",qaa:"mainPlaylistEntity",raa:"mainPlaylistVideoEntity",saa:"mainVideoEntity",taa:"mainVideoDownloadStateEntity",Aca:"musicAlbumReleaseDetail",Bca:"musicAlbumReleaseDownloadMetadataEntity",Cca:"musicAlbumRelease",Dca:"musicAlbumReleaseUserDetail",Eca:"musicArtistDetail",Fca:"musicArtist",Hca:"musicArtistUserDetail",Qca:"musicLibraryEdit",Rca:"musicLibraryStatusEntity",cda:"musicShare",hda:"musicTrackDetail",
ida:"musicTrackDownloadMetadataEntity",jda:"musicTrack",kda:"musicTrackUserDetail",Ada:"offlineOrchestrationActionWrapperEntity",Kda:"offlineVideoPolicy",Lda:"offlineVideoStreams",xea:"playbackData",Afa:"orchestrationWebSamplingEntity",Iga:"downloadsPageViewConfigurationEntity",Jga:"refresh",Kga:"mainDownloadsListEntity",Lga:"downloadsPageRefreshTokenEntity",tha:"transfer"};g.w(j5,g.I);j5.prototype.B=function(a){this.api.La("onOfflineOperationFailure",a.data)};
j5.prototype.C=function(a){this.api.X("offlinetransferpause",a.data)};
j5.prototype.ea=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};VZa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};YZa.prototype.uf=function(){this.j&&l5(this)};var r5=g.C.caches,q5,s5;n5.prototype.open=function(a){return r5.open(p5(a))};
n5.prototype.has=function(a){return r5.has(p5(a))};
n5.prototype.delete=function(a){return r5.delete(p5(a))};
n5.prototype.match=function(a,b){var c=this,d,e,f,h,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Ra(5);break}h=f.value;return g.A(n,c.open(h),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Ra(3);break;case 5:return n.return()}})};
g.w(o5,n5);o5.prototype.keys=function(){var a,b,c,d,e,f,h,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.Br("CacheStorage keys"),g.A(n,r5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");h=-1===p?{MC:f}:{MC:f.substring(0,p),datasyncId:f.substring(p+1)};l=h.MC;m=h.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(d1a).map(function(a){return d1a[a]});
var l_a="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainPlaylistEntity mainVideoEntity mainVideoDownloadStateEntity musicArtist musicTrack musicTrackDownloadMetadataEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(H5,F5);H5.prototype.u=function(a){return x5(a)?s_a(this,a):y5(a)?t_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(J5,F5);J5.prototype.u=function(a){return x5(a)?w_a(this,a):y5(a)?x_a(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
J5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=w5(a),g.A(f,e5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,d5(b.j,d,"transfer"),5);case 5:e=g.FC(d.key).entityId;m5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,mj:d});g.xa(f,4);break;case 3:return g.ya(f),f.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var N_a=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var M5;F_a.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(P5,g.I);P5.prototype.ea=function(){this.J&&this.J();g.I.prototype.ea.call(this)};
P5.prototype.createAction=function(a,b){var c=g.FC(a.entityKey).entityType,d=g.Hu(16);return new K5(c,d,a,b.actionId,b.rootActionId)};
P5.prototype.W=function(a){var b=this,c,d,e,f,h,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(h=f.next();!h.done;h=f.next())l=h.value,m=g.FC(l),n=m.entityId,H_a(b.j,n)||e.push(l);return g.A(q,P_a(b,e),2)}p=q.u;return g.A(q,R5(b,p),0)})};
P5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,Q_a(a),0)})};g.k=W_a.prototype;g.k.fZ=function(a){var b=this,c,d,e;return g.B(function(f){if(!g.V(a.state,128))return f.Ra(0);var h=null==(c=a.state.getData())?void 0:c.errorCode;a.state.getData();var l=null==(d=a.state.getData())?void 0:d.mB;e="net.connect"===h&&1===l?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==h?0:h.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(f,b.qs(b.player.getVideoData().videoId,e),0)})};
g.k.qs=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(T5(c,a,!1,!0),d.Ra(0)):g.A(d,S5(c,a),3)}g.SC(a,4);return g.A(d,c.j.qs(b),0)})};
g.k.EC=function(a){2===a.status?(a.status!==this.B&&(Y5(this.j),g.SC(a.videoId,2)),a.kz&&q0a(this.j,a.videoId,a.kz)):4===a.status?(S5(this,a.videoId),this.qs(a.videoId,a.UB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&o0a(this.j);this.B=a.status;this.api.La("localmediachange",{videoId:a.videoId,status:a.status})};
g.k.rI=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,S5(a,b),2)}return g.A(c,a.j.rI(),0)})};
g.k.K=function(a){return this.api.S().K(a)};g.w(U5,g.I);U5.prototype.ea=function(){this.u&&this.u();g.I.prototype.ea.call(this)};
U5.prototype.B=function(a){var b=this,c,d,e,f,h,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(h=f.next();!h.done;h=f.next())l=h.value,m=g.FC(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,c0a(b,e),0)})};g.w(V5,g.I);g.k=V5.prototype;g.k.ea=function(){this.J&&this.J();this.N.dispose();this.C.dispose();this.Y&&g.$e(this.D.B,this.Y);this.W&&g.$e(this.D.B,this.W);g.I.prototype.ea.call(this)};
g.k.r0=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.GC(a,"transfer"),b.j&&c===b.j.key?(T5(b.I,b.B,!0),b.C.stop(),e.Ra(0)):g.A(e,b5(b.u,{mode:"readwrite",jc:!0},function(f){return T4(f,c,"transfer").then(function(h){if(h&&"TRANSFER_STATE_COMPLETE"!==h.transferState&&"TRANSFER_STATE_FAILED"!==h.transferState)return h.transferState="TRANSFER_STATE_PAUSED_BY_USER",W4(f,h,"transfer").then(function(){return h})})}),3);
(d=e.u)&&d_a({videoId:a,mj:d});g.va(e)})};
g.k.q0=function(){this.j&&this.B&&T5(this.I,this.B,!1);this.C.stop()};
g.k.xz=function(){this.j?i0a(this,this.j):X5(this)};
g.k.VS=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Ra(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Ra(3);break}c=b;return g.A(d,e5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Ra(3);break}return g.A(d,j0a(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,X5(b),0)}})};
g.k.qs=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var h=!1;break a;default:h=!0}return h&&r0a(c)?g.A(f,$5(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,s0a(c,a),3)}3!=f.j&&(d=g.FC(c.j.key).entityId,m5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,mj:c.j}));W5(c);e=X5(c,!0);b&&b(e);g.va(f)})};
g.k.rI=function(a){var b=this,c,d,e,f,h,l;return g.B(function(m){if(1==m.j)return r0a(b)?g.A(m,$5(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,s0a(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.FC(b.j.key).entityId,m5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,mj:b.j}),d=z_a(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.GC(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},h=L5(new K5("playbackData",c,f)),g.A(m,d5(b.u,h,"offlineOrchestrationActionWrapperEntity"),3);W5(b);l=X5(b,!0);a&&a(l);g.va(m)})};
var l6={},a6=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.k=b6.prototype;g.k.Px=function(a){var b={};return b.playbackData=new H5(a,this.U,this.u),b.transfer=new J5(a),b};
g.k.jJ=function(){var a=this;return g.B(function(b){return a.j?g.A(b,g0a(a.j),0):b.Ra(0)})};
g.k.isOrchestrationLeader=function(){return this.B.j};
g.k.II=function(a){var b=this.u;b.api.X("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.k.xz=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,h5(),2);b=d.u;if(!b)return d.return();c=g.GC(a,"transfer");return g.A(d,b5(b,{mode:"readwrite",jc:!0},function(e){return T4(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",W4(e,f,"transfer").then(function(){m5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,mj:f});return g.Mr.resolve(null)})):
g.Mr.resolve(null)})}),0)})};
g.k.rz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,h,l,m,n;return g.B(function(p){if(1==p.j)return b.N.tf()?g.A(p,h5(),2):p.return(x0a());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,f5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];h=g.r(e);for(l=h.next();!l.done;l=h.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.FC(m.key).entityId,f.push(n));return f.length?p.return(c6(b,f,b.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.k.deleteAll=function(){return c6(this,["!*$_ALL_ENTITIES_!*$"],this.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(e6,F5);e6.prototype.u=function(a){return x5(a)?C0a(this,a):z5(a)?D0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var B0a=[10];g.w(f6,F5);f6.prototype.u=function(a){return x5(a)?K0a(this,a):y5(a)?L0a(this,a):z5(a)?M0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var O0a=[10];g.w(g6,F5);g6.prototype.u=function(a){return x5(a)?R0a(this,a):y5(a)?S0a(this,a):z5(a)?T0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var V0a=[10];g.w(h6,b6);h6.prototype.Px=function(a){var b=b6.prototype.Px.call(this,a);b.ytMainDownloadedVideoEntity=new g6(a,this.U,this.u);b.mainVideoEntity=new f6(a,this.U,this.u);b.mainPlaylistEntity=new e6(a,this.U,this.u);return b};
h6.prototype.jJ=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,b6.prototype.jJ.call(a),2):a.U.K("woffle_entity_migration")?g.A(b,W0a(),0):b.Ra(0)})};g.w(i6,F5);i6.prototype.u=function(a){return x5(a)?Z0a(this,a):y5(a)?$0a(this,a):z5(a)?a1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var c1a=[10];g.w(j6,b6);j6.prototype.Px=function(a){var b=b6.prototype.Px.call(this,a);b.musicTrack=new i6(a,this.U,this.u);return b};g.w(k6,g.WI);g.k=k6.prototype;g.k.create=function(){var a=this.player.S();g.SB(a)?this.j=new h6(a,this.player):g.gB(a)&&(this.j=new j6(a,this.player))};
g.k.hj=function(){return!1};
g.k.VI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(c6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.k.deleteAll=function(){return this.j.deleteAll()};
g.k.rz=function(a){return this.j.rz(a)};
g.k.II=function(a){this.j.II(a)};
g.k.xz=function(a){return this.j.xz(a)};
g.k.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.VI("offline",k6);})(_yt_player);
